export const CATALOG_CATEGORIES = [
  "Barn og unge",
  "Demografi og boforhold",
  "Helse og eldre",
  "Flyktninger og asylsøkere",
  "Frivillighet",
  "Økonomi",
] as const;

export type CatalogCategory = (typeof CATALOG_CATEGORIES)[number];
export type CatalogStatus = "metadata-only" | "api-known" | "integrated";
export type ValueType = "count" | "percent" | "rate" | "kroner" | "duration" | "unknown";
export type GeographyType = "municipality" | "county" | "norway" | "school" | "branch" | "unknown";
export type TimeDimension = "year" | "month" | "school-year" | "count-date" | "unknown";

export type RelatedStatistic = {
  title: string;
  path?: string;
};

export type SourceTable = {
  id: string;
  label: string;
};

export type AboutNumbers = {
  statisticName?: string;
  sourceDescription?: string;
  dataType?: string;
  countDate?: string;
  collectionMethod?: string;
  definitions?: string[];
  references?: string[];
};

export type SamfunnspulsCatalogEntry = {
  slug: string;
  path: string;
  title: string;
  category: CatalogCategory;
  summary?: string;
  source: string;
  status: CatalogStatus;
  powerBiReportId?: string;
  powerBiReportName?: string;
  ssbTables?: SourceTable[];
  otherApiHints?: string[];
  valueTypes: ValueType[];
  geographies: GeographyType[];
  timeDimensions: TimeDimension[];
  relatedStatistics?: RelatedStatistic[];
  aboutNumbers?: AboutNumbers;
  tags: string[];
};

const SSB = "Statistisk sentralbyrå (SSB)";
const UDIR = "Utdanningsdirektoratet (Udir)";
const NAV = "NAV";
const IMDI = "Integrerings- og mangfoldsdirektoratet (IMDi)";
const RODE_KORS = "Røde Kors";
const BRREG = "Brønnøysundregistrene";

export const SAMFUNNSPULS_CATALOG: SamfunnspulsCatalogEntry[] = [
  {
    slug: "aldersgrupper_bosted",
    path: "/utforsk-data/barn-og-unge/aldersgrupper_bosted",
    title: "Antall barn og unge under 19 år, etter aldersgruppe og bosted",
    category: "Barn og unge",
    summary: "Viser hvor mange barn og unge som bor i et område, fordelt på aldersgrupper og bosted.",
    source: SSB,
    status: "api-known",
    powerBiReportId: "517f6fd6-0ae1-4132-857a-31a1d379c2b8",
    otherApiHints: ["SSB spesialbestilt statistikk"],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["barn", "unge", "alder", "bosted", "befolkning"],
  },
  {
    slug: "barn-og-unge-som-bor-trangt-romslig-uoppgitt",
    path: "/utforsk-data/barn-og-unge/barn-og-unge-som-bor-trangt-romslig-uoppgitt",
    title: "Barn og unge som bor trangt/romslig/uoppgitt",
    category: "Barn og unge",
    summary: "Beskriver boforhold for barn og unge med kategorier for trangt, romslig og uoppgitt bolig.",
    source: SSB,
    status: "api-known",
    powerBiReportId: "d67bcbd0-3975-417b-a6ec-d85368f3149c",
    valueTypes: ["count", "percent"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    relatedStatistics: [{ title: "Barn og unge i husholdninger med lavinntekt (EU-60)", path: "/utforsk-data/barn-og-unge/lavinntekt" }],
    tags: ["barn", "unge", "boforhold", "trangboddhet", "bolig"],
  },
  {
    slug: "mobbing-pa-skolen",
    path: "/utforsk-data/barn-og-unge/mobbing-pa-skolen",
    title: "Andel elever på 7. og 10. trinn som har blitt mobbet",
    category: "Barn og unge",
    summary: "Viser andel elever i grunnskolen som oppgir at de har blitt mobbet.",
    source: UDIR,
    status: "api-known",
    powerBiReportId: "af3083c3-e573-4fe2-b540-65dfb6c60b73",
    otherApiHints: ["Elevundersøkelsen", "Skoleporten"],
    valueTypes: ["percent"],
    geographies: ["municipality", "county", "school"],
    timeDimensions: ["school-year"],
    tags: ["mobbing", "skole", "grunnskole", "elever", "udir"],
  },
  {
    slug: "mobbing-pa-skolen-vg1",
    path: "/utforsk-data/barn-og-unge/mobbing-pa-skolen-vg1",
    title: "Andel elever på Vg1 som har blitt mobbet",
    category: "Barn og unge",
    summary: "Viser andel elever på Vg1 som oppgir at de har blitt mobbet.",
    source: UDIR,
    status: "metadata-only",
    otherApiHints: ["Elevundersøkelsen", "Skoleporten"],
    valueTypes: ["percent"],
    geographies: ["county", "school"],
    timeDimensions: ["school-year"],
    tags: ["mobbing", "videregående", "vg1", "elever", "udir"],
  },
  {
    slug: "stotte-hjemmefra-til-skolearbeidet",
    path: "/utforsk-data/barn-og-unge/stotte-hjemmefra-til-skolearbeidet",
    title: "Støtte hjemmefra til skolearbeidet - grunnskolen",
    category: "Barn og unge",
    summary: "Måler elevers opplevelse av støtte hjemmefra til skolearbeid i grunnskolen.",
    source: UDIR,
    status: "metadata-only",
    otherApiHints: ["Elevundersøkelsen", "Skoleporten"],
    valueTypes: ["percent"],
    geographies: ["municipality", "county", "school"],
    timeDimensions: ["school-year"],
    tags: ["skole", "skolearbeid", "foreldre", "hjemmestøtte", "grunnskole"],
  },
  {
    slug: "stotte-hjemmefra-til-skolearbeidet-1",
    path: "/utforsk-data/barn-og-unge/stotte-hjemmefra-til-skolearbeidet-1",
    title: "Støtte hjemmefra til skolearbeidet - Vg1",
    category: "Barn og unge",
    summary: "Måler elevers opplevelse av støtte hjemmefra til skolearbeid på Vg1.",
    source: UDIR,
    status: "metadata-only",
    otherApiHints: ["Elevundersøkelsen", "Skoleporten"],
    valueTypes: ["percent"],
    geographies: ["county", "school"],
    timeDimensions: ["school-year"],
    tags: ["skole", "skolearbeid", "foreldre", "hjemmestøtte", "vg1"],
  },
  {
    slug: "registrert-fravaer-i-grunnskolen-10-trinn",
    path: "/utforsk-data/barn-og-unge/registrert-fravaer-i-grunnskolen-10-trinn",
    title: "Registrert fravær i grunnskolen (10. trinn)",
    category: "Barn og unge",
    summary: "Viser registrert fravær for elever på 10. trinn.",
    source: UDIR,
    status: "metadata-only",
    otherApiHints: ["Grunnskolens informasjonssystem", "Skoleporten"],
    valueTypes: ["count", "rate"],
    geographies: ["municipality", "county", "school"],
    timeDimensions: ["school-year"],
    tags: ["fravær", "grunnskole", "10 trinn", "skole", "udir"],
  },
  {
    slug: "registrert-fravaer-i-videregaende-skole",
    path: "/utforsk-data/barn-og-unge/registrert-fravaer-i-videregaende-skole",
    title: "Registrert fravær i videregående skole",
    category: "Barn og unge",
    summary: "Viser registrert fravær i videregående opplæring.",
    source: UDIR,
    status: "metadata-only",
    otherApiHints: ["Skoleporten"],
    valueTypes: ["count", "rate"],
    geographies: ["county", "school"],
    timeDimensions: ["school-year"],
    tags: ["fravær", "videregående", "skole", "udir"],
  },
  {
    slug: "andel-elever-som-har-sluttet-i-videregaende-opplaering-i-lopet-av-skolearet",
    path: "/utforsk-data/barn-og-unge/andel-elever-som-har-sluttet-i-videregaende-opplaering-i-lopet-av-skolearet",
    title: "Andel elever som har sluttet på videregående skole",
    category: "Barn og unge",
    summary: "Viser andel elever som slutter i videregående opplæring i løpet av skoleåret.",
    source: UDIR,
    status: "metadata-only",
    otherApiHints: ["Skoleporten"],
    valueTypes: ["percent"],
    geographies: ["county", "school"],
    timeDimensions: ["school-year"],
    tags: ["frafall", "videregående", "sluttet", "skole", "udir"],
  },
  {
    slug: "lavinntekt",
    path: "/utforsk-data/barn-og-unge/lavinntekt",
    title: "Barn og unge i husholdninger med lavinntekt (EU-60)",
    category: "Barn og unge",
    summary:
      "Viser antall barn og unge under 18 år som vokser opp i husholdninger med inntekt under 60 prosent av medianinntekten.",
    source: SSB,
    status: "integrated",
    powerBiReportId: "7d926ca6-0cf0-4b69-86bc-93c46728471b",
    powerBiReportName: "ssb-08764",
    ssbTables: [{ id: "08764", label: "Barn under 18 år i husholdninger med lavinntekt" }],
    valueTypes: ["count", "percent"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year", "count-date"],
    relatedStatistics: [
      {
        title: "Personer i husholdninger med lavinntekt (EU-60), hele befolkningen",
        path: "/utforsk-data/okonomi/personer-som-tilhorer-husholdninger-med-lavinntekt-eu-60-hele-befolkningen",
      },
      {
        title: "Barn og unge som bor trangt/romslig/uoppgitt",
        path: "/utforsk-data/barn-og-unge/barn-og-unge-som-bor-trangt-romslig-uoppgitt",
      },
      { title: "Antall sosialhjelpsmottakere", path: "/utforsk-data/okonomi/antall-sosialhjelpsmottakere" },
      { title: "Antall familier, etter familietype", path: "/utforsk-data/demografi-og-boforhold/antall-familier-etter-familietype" },
    ],
    aboutNumbers: {
      statisticName: "Antall barn og unge under 18 år som tilhører husholdninger med lavinntekt (EU-60)",
      sourceDescription: "Statistisk sentralbyrå (SSB), statistikkbanktabell 08764",
      dataType: "registerdata",
      countDate: "31. desember",
      collectionMethod: "fra SSBs åpne API",
      definitions: [
        "Lavinntektshusholdninger er husholdninger med samlet inntekt under 60 prosent av medianinntekten i befolkningen.",
        "Antall personer i husholdninger med lavinntekt (EU-60) er et mål på relativ fattigdom.",
        "Medianinntekten deler en gruppe i to like store halvdeler etter at inntekten er sortert.",
        "EU-60 bruker inntekt etter skatt per forbruksenhet, beregnet med EU-ekvivalensskala.",
        "I EU-ekvivalensskala får første voksne vekt 1, neste voksne vekt 0,5, og hvert barn vekt 0,3.",
      ],
      references: [
        "Store norske leksikon: Fattigdom",
        "Barne- og familiedepartementet: Like muligheter i oppveksten",
        "SSB: Økonomi og levekår for ulike lavinntektsgrupper",
        "SSB: Variabeldefinisjon, EU-ekvivalensskala",
      ],
    },
    tags: ["barn", "unge", "lavinntekt", "fattigdom", "EU-60", "medianinntekt", "08764"],
  },
  {
    slug: "nokkeltall-for-grunnskoler",
    path: "/utforsk-data/barn-og-unge/nokkeltall-for-grunnskoler",
    title: "Nøkkeltall for grunnskoler",
    category: "Barn og unge",
    summary: "Samler sentrale nøkkeltall for grunnskoler.",
    source: "Utdanningsdirektoratet (Udir) og Statistisk sentralbyrå (SSB)",
    status: "metadata-only",
    otherApiHints: ["Skoleporten", "SSB"],
    valueTypes: ["count", "percent", "rate"],
    geographies: ["municipality", "county", "school"],
    timeDimensions: ["school-year", "year"],
    tags: ["grunnskole", "skole", "nøkkeltall", "elever", "udir", "ssb"],
  },
  {
    slug: "antall-kommunale-fritidssenter",
    path: "/utforsk-data/barn-og-unge/antall-kommunale-fritidssenter",
    title: "Kommunale fritidstilbud - antall kommunale fritidssenter",
    category: "Barn og unge",
    summary: "Viser antall kommunale fritidssenter i kommunen.",
    source: SSB,
    status: "metadata-only",
    otherApiHints: ["KOSTRA"],
    valueTypes: ["count"],
    geographies: ["municipality", "county"],
    timeDimensions: ["year"],
    tags: ["fritid", "fritidssenter", "kommune", "KOSTRA", "barn", "unge"],
  },
  {
    slug: "kommunale-fritidstilbud-antall-frivillige-barne-og-ungdomsforeninger-som-far-kommunalt-tilskudd",
    path: "/utforsk-data/barn-og-unge/kommunale-fritidstilbud-antall-frivillige-barne-og-ungdomsforeninger-som-far-kommunalt-tilskudd",
    title: "Kommunale fritidstilbud - antall frivillige foreninger",
    category: "Barn og unge",
    summary: "Viser antall frivillige barne- og ungdomsforeninger som mottar kommunalt tilskudd.",
    source: SSB,
    status: "metadata-only",
    otherApiHints: ["KOSTRA"],
    valueTypes: ["count"],
    geographies: ["municipality", "county"],
    timeDimensions: ["year"],
    tags: ["fritid", "frivillige foreninger", "kommunalt tilskudd", "KOSTRA", "barn", "unge"],
  },
  {
    slug: "kommunale-fritidstilbud-tilskudd-overforinger-til-frivillige-barne-og-ungdomsforeninger-per-lag-som-mottar-tilskudd",
    path: "/utforsk-data/barn-og-unge/kommunale-fritidstilbud-tilskudd-overforinger-til-frivillige-barne-og-ungdomsforeninger-per-lag-som-mottar-tilskudd",
    title: "Kommunale fritidstilbud - tilskudd per lag",
    category: "Barn og unge",
    summary: "Viser kommunale overføringer til frivillige barne- og ungdomsforeninger per lag som mottar tilskudd.",
    source: SSB,
    status: "metadata-only",
    otherApiHints: ["KOSTRA"],
    valueTypes: ["kroner"],
    geographies: ["municipality", "county"],
    timeDimensions: ["year"],
    tags: ["fritid", "tilskudd", "overføringer", "frivillige foreninger", "KOSTRA"],
  },
  {
    slug: "vedvarende_lavinntekt_barn_unge",
    path: "/utforsk-data/barn-og-unge/vedvarende_lavinntekt_barn_unge",
    title: "Barn og unge under 18 år i husholdninger med vedvarende lavinntekt (EU-skala 60 prosent)",
    category: "Barn og unge",
    summary: "Viser barn og unge som lever i husholdninger med vedvarende lavinntekt målt med EU-skala 60 prosent.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count", "percent"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    relatedStatistics: [{ title: "Barn og unge i husholdninger med lavinntekt (EU-60)", path: "/utforsk-data/barn-og-unge/lavinntekt" }],
    tags: ["barn", "unge", "vedvarende lavinntekt", "EU-skala", "fattigdom"],
  },
  {
    slug: "befolkningsendring-folketilvekst",
    path: "/utforsk-data/demografi-og-boforhold/befolkningsendring-folketilvekst",
    title: "Befolkningsendring",
    category: "Demografi og boforhold",
    summary: "Gir oversikt over folketilvekst, altså hvor mye befolkningen i et valgt område har økt eller sunket i løpet av et år.",
    source: SSB,
    status: "api-known",
    powerBiReportId: "92bfaba4-445d-4581-a6d0-0d4b103f146f",
    powerBiReportName: "ssb-06913",
    ssbTables: [{ id: "06913", label: "Endringer i kommuner, fylker og hele landets befolkning" }],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year", "count-date"],
    relatedStatistics: [
      { title: "Levendefødte", path: "/utforsk-data/demografi-og-boforhold/antall-levendefodte" },
      { title: "Tilflytting", path: "/utforsk-data/demografi-og-boforhold/endringer-i-befolkningen-tilflytting" },
    ],
    aboutNumbers: {
      statisticName: "Endringer i kommuner, fylker og hele landets befolkning - folketilvekst",
      sourceDescription: "Statistisk sentralbyrå (SSB), statistikkbanktabell 06913",
      dataType: "registerdata",
      countDate: "31.12",
      collectionMethod: "fra SSBs åpne API",
    },
    tags: ["befolkning", "befolkningsendring", "folketilvekst", "demografi", "06913"],
  },
  {
    slug: "antall-levendefodte",
    path: "/utforsk-data/demografi-og-boforhold/antall-levendefodte",
    title: "Levendefødte",
    category: "Demografi og boforhold",
    summary: "Viser antall levendefødte i et valgt område.",
    source: SSB,
    status: "api-known",
    powerBiReportId: "92bfaba4-445d-4581-a6d0-0d4b103f146f",
    powerBiReportName: "ssb-06913",
    ssbTables: [{ id: "06913", label: "Endringer i kommuner, fylker og hele landets befolkning" }],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    relatedStatistics: [{ title: "Befolkningsendring", path: "/utforsk-data/demografi-og-boforhold/befolkningsendring-folketilvekst" }],
    tags: ["fødte", "levendefødte", "befolkning", "demografi", "06913"],
  },
  {
    slug: "endringer-i-befolkningen-tilflytting",
    path: "/utforsk-data/demografi-og-boforhold/endringer-i-befolkningen-tilflytting",
    title: "Tilflytting",
    category: "Demografi og boforhold",
    summary: "Viser tilflytting til et valgt område som del av befolkningsendringer.",
    source: SSB,
    status: "api-known",
    ssbTables: [{ id: "06913", label: "Endringer i kommuner, fylker og hele landets befolkning" }],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    relatedStatistics: [{ title: "Befolkningsendring", path: "/utforsk-data/demografi-og-boforhold/befolkningsendring-folketilvekst" }],
    tags: ["tilflytting", "flytting", "befolkning", "demografi", "06913"],
  },
  {
    slug: "antall-personer-etter-alder-og-kjonn",
    path: "/utforsk-data/demografi-og-boforhold/antall-personer-etter-alder-og-kjonn",
    title: "Antall personer, etter alder og kjønn",
    category: "Demografi og boforhold",
    summary: "Viser befolkningen fordelt etter alder og kjønn.",
    source: SSB,
    status: "api-known",
    powerBiReportId: "65b6a7b5-c273-4ef3-b110-40198e27537d",
    ssbTables: [
      { id: "04362", label: "Befolkning, etter kjønn og alder" },
      { id: "07459", label: "Befolkning, etter alder og kjønn" },
      { id: "10826", label: "Befolkning, etter region, kjønn, alder og statistikkvariabel" },
    ],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["befolkning", "alder", "kjønn", "demografi", "04362", "07459", "10826"],
  },
  {
    slug: "alder_husholdningstype_bosted",
    path: "/utforsk-data/demografi-og-boforhold/alder_husholdningstype_bosted",
    title: "Antall personer, etter aldersgruppe, husholdningstype og bosted",
    category: "Demografi og boforhold",
    summary: "Viser personer fordelt etter alder, husholdningstype og bosted.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["befolkning", "alder", "husholdningstype", "bosted", "demografi"],
  },
  {
    slug: "antall-familier-etter-familietype",
    path: "/utforsk-data/demografi-og-boforhold/antall-familier-etter-familietype",
    title: "Antall familier, etter familietype",
    category: "Demografi og boforhold",
    summary: "Viser antall familier fordelt etter familietype.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    relatedStatistics: [{ title: "Barn og unge i husholdninger med lavinntekt (EU-60)", path: "/utforsk-data/barn-og-unge/lavinntekt" }],
    tags: ["familier", "familietype", "husholdning", "demografi"],
  },
  {
    slug: "antall-personer-16-ar-og-over-etter-utdanningsniva-og-kjonn",
    path: "/utforsk-data/demografi-og-boforhold/antall-personer-16-ar-og-over-etter-utdanningsniva-og-kjonn",
    title: "Antall personer i alderen 16 år og over, etter utdanningsnivå og kjønn",
    category: "Demografi og boforhold",
    summary: "Viser personer fra 16 år og oppover fordelt etter utdanningsnivå og kjønn.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count", "percent"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["utdanning", "utdanningsnivå", "kjønn", "befolkning", "demografi"],
  },
  {
    slug: "sykehjem",
    path: "/utforsk-data/helse-og-eldre/sykehjem",
    title: "Antall beboere i sykehjem",
    category: "Helse og eldre",
    summary: "Viser antall beboere i sykehjem.",
    source: SSB,
    status: "api-known",
    powerBiReportId: "1210933a-41bb-434c-aed4-0db038b76b8c",
    ssbTables: [{ id: "12292", label: "Beboere i institusjon" }],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year", "count-date"],
    tags: ["sykehjem", "eldre", "helse", "institusjon", "12292"],
  },
  {
    slug: "brukere-av-hjemmetjeneste",
    path: "/utforsk-data/helse-og-eldre/brukere-av-hjemmetjeneste",
    title: "Antall personer som bruker hjemmetjeneste",
    category: "Helse og eldre",
    summary: "Viser antall personer som mottar hjemmetjenester.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["hjemmetjeneste", "eldre", "helse", "omsorg"],
  },
  {
    slug: "bosetting-av-flyktninger",
    path: "/utforsk-data/asylsokere-flyktninger-og-migrasjon/bosetting-av-flyktninger",
    title: "Bosetting av flyktninger",
    category: "Flyktninger og asylsøkere",
    summary: "Viser bosetting av flyktninger i kommuner og fylker.",
    source: IMDI,
    status: "api-known",
    powerBiReportId: "8317274a-bd9f-4eb1-b87c-ef97460085b3",
    otherApiHints: ["IMDi bosettingstall"],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["flyktninger", "bosetting", "asyl", "migrasjon", "imdi"],
  },
  {
    slug: "innvandrere-etter-innvandringsgrunn-og-kjonn",
    path: "/utforsk-data/asylsokere-flyktninger-og-migrasjon/innvandrere-etter-innvandringsgrunn-og-kjonn",
    title: "Antall innvandrere, etter innvandringsgrunn og kjønn",
    category: "Flyktninger og asylsøkere",
    summary: "Viser innvandrere fordelt etter innvandringsgrunn og kjønn.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["innvandrere", "innvandringsgrunn", "kjønn", "migrasjon", "flyktninger"],
  },
  {
    slug: "innvandrere-etter-landbakgrunn",
    path: "/utforsk-data/asylsokere-flyktninger-og-migrasjon/innvandrere-etter-landbakgrunn",
    title: "Antall innvandrere, etter landbakgrunn",
    category: "Flyktninger og asylsøkere",
    summary: "Viser innvandrere fordelt etter landbakgrunn.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["innvandrere", "landbakgrunn", "migrasjon", "flyktninger"],
  },
  {
    slug: "medlemmer-i-rode-kors-arsrapport",
    path: "/utforsk-data/frivillighet/medlemmer-i-rode-kors-arsrapport",
    title: "Medlemmer i Røde Kors - årsrapport",
    category: "Frivillighet",
    summary: "Viser medlemstall fra Røde Kors årsrapport.",
    source: RODE_KORS,
    status: "api-known",
    powerBiReportId: "3bb287aa-a8d6-4094-b0d1-f017b197acf7",
    otherApiHints: ["Røde Kors årsrapport"],
    valueTypes: ["count"],
    geographies: ["branch", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["Røde Kors", "medlemmer", "frivillighet", "årsrapport"],
  },
  {
    slug: "frivillige-i-rode-kors-arsrapport",
    path: "/utforsk-data/frivillighet/frivillige-i-rode-kors-arsrapport",
    title: "Frivillige i Røde Kors - årsrapport",
    category: "Frivillighet",
    summary: "Viser frivilligtall fra Røde Kors årsrapport.",
    source: RODE_KORS,
    status: "metadata-only",
    otherApiHints: ["Røde Kors årsrapport"],
    valueTypes: ["count"],
    geographies: ["branch", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["Røde Kors", "frivillige", "frivillighet", "årsrapport"],
  },
  {
    slug: "organisasjoner-som-er-registrert-i-frivillighetsregisteret",
    path: "/utforsk-data/frivillighet/organisasjoner-som-er-registrert-i-frivillighetsregisteret",
    title: "Organisasjoner som er registrert i Frivillighetsregisteret",
    category: "Frivillighet",
    summary: "Viser organisasjoner registrert i Frivillighetsregisteret.",
    source: BRREG,
    status: "metadata-only",
    otherApiHints: ["Frivillighetsregisteret", "Enhetsregisteret"],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["frivillighet", "Frivillighetsregisteret", "organisasjoner", "Brønnøysundregistrene"],
  },
  {
    slug: "personer-som-tilhorer-husholdninger-med-lavinntekt-eu-60-hele-befolkningen",
    path: "/utforsk-data/okonomi/personer-som-tilhorer-husholdninger-med-lavinntekt-eu-60-hele-befolkningen",
    title: "Personer i husholdninger med lavinntekt (EU-60), hele befolkningen",
    category: "Økonomi",
    summary: "Viser personer i hele befolkningen som tilhører husholdninger med lavinntekt etter EU-60.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count", "percent"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    relatedStatistics: [{ title: "Barn og unge i husholdninger med lavinntekt (EU-60)", path: "/utforsk-data/barn-og-unge/lavinntekt" }],
    tags: ["lavinntekt", "fattigdom", "EU-60", "økonomi", "husholdninger"],
  },
  {
    slug: "vedvarende_lavinntekt",
    path: "/utforsk-data/okonomi/vedvarende_lavinntekt",
    title: "Personer i husholdninger med vedvarende lavinntekt (EU-skala 60 prosent), etter alder",
    category: "Økonomi",
    summary: "Viser personer i husholdninger med vedvarende lavinntekt fordelt etter alder.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["count", "percent"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["vedvarende lavinntekt", "EU-skala", "fattigdom", "økonomi", "alder"],
  },
  {
    slug: "registrerte-arbeidsledige-etter-maned",
    path: "/utforsk-data/okonomi/registrerte-arbeidsledige-etter-maned",
    title: "Registrerte helt arbeidsledige, etter måned",
    category: "Økonomi",
    summary: "Viser registrerte helt arbeidsledige etter måned.",
    source: NAV,
    status: "api-known",
    powerBiReportId: "70e38d9f-e117-49c3-9462-1876e205f5a5",
    otherApiHints: ["NAV åpen statistikk for arbeidssøkere og stillinger"],
    valueTypes: ["count", "percent"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["month"],
    tags: ["NAV", "arbeidsledige", "arbeidsledighet", "økonomi", "måned"],
  },
  {
    slug: "antall-sosialhjelpsmottakere",
    path: "/utforsk-data/okonomi/antall-sosialhjelpsmottakere",
    title: "Antall sosialhjelpsmottakere",
    category: "Økonomi",
    summary: "Viser antall mottakere av økonomisk sosialhjelp.",
    source: SSB,
    status: "api-known",
    powerBiReportId: "8e57dbe8-ebe5-40f9-967b-a0876c7ceac7",
    ssbTables: [{ id: "13995", label: "Sosialhjelpsmottakere" }],
    valueTypes: ["count"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    relatedStatistics: [{ title: "Barn og unge i husholdninger med lavinntekt (EU-60)", path: "/utforsk-data/barn-og-unge/lavinntekt" }],
    tags: ["sosialhjelp", "sosialhjelpsmottakere", "økonomi", "13995"],
  },
  {
    slug: "stonadssatser-for-sosialhjelp",
    path: "/utforsk-data/okonomi/stonadssatser-for-sosialhjelp",
    title: "Stønadssatser for sosialhjelp",
    category: "Økonomi",
    summary: "Viser stønadssatser for økonomisk sosialhjelp.",
    source: NAV,
    status: "metadata-only",
    otherApiHints: ["NAV", "kommunale satser"],
    valueTypes: ["kroner"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["sosialhjelp", "stønadssatser", "økonomi", "NAV"],
  },
  {
    slug: "okonomisk-sosialhjelp-gjennomsnittlig-stonadstid",
    path: "/utforsk-data/okonomi/okonomisk-sosialhjelp-gjennomsnittlig-stonadstid",
    title: "Økonomisk sosialhjelp - gjennomsnittlig stønadstid",
    category: "Økonomi",
    summary: "Viser gjennomsnittlig stønadstid for mottakere av økonomisk sosialhjelp.",
    source: SSB,
    status: "metadata-only",
    valueTypes: ["duration"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["sosialhjelp", "stønadstid", "økonomi", "varighet"],
  },
  {
    slug: "utgifter-som-inngar-i-stonadssatsene-for-okonomisk-sosialhjelp",
    path: "/utforsk-data/okonomi/utgifter-som-inngar-i-stonadssatsene-for-okonomisk-sosialhjelp",
    title: "Økonomisk sosialhjelp - beregningsgrunnlag",
    category: "Økonomi",
    summary: "Beskriver utgifter som inngår i stønadssatsene for økonomisk sosialhjelp.",
    source: "Statistisk sentralbyrå (SSB) og NAV",
    status: "metadata-only",
    otherApiHints: ["SSB", "NAV"],
    valueTypes: ["kroner"],
    geographies: ["municipality", "county", "norway"],
    timeDimensions: ["year"],
    tags: ["sosialhjelp", "beregningsgrunnlag", "utgifter", "økonomi", "NAV", "SSB"],
  },
];
